#!/usr/bin/env bash
# Fixes Nginx to run as nginx user and listen on port 8080
sudo useradd --system --no-create-home --shell /bin/false nginx || true
sudo sed -Ei 's/^(\s*user\s+).*/\1nginx;/' /etc/nginx/nginx.conf
sudo sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
sudo pkill apache2
sudo service nginx restart
