#!/usr/bin/env bash
# Configures the server to listen on port 80 of all IPv4 IPs
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo systemctl restart nginx
echo "" | sudo tee /run/nginx.pid > /dev/null
